name: flutterwanandroid
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  pedantic: ^1.9.0
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0
  dio: ^3.0.9
  cookie_jar: ^1.0.1
  dio_cookie_manager: ^1.0.0
  shared_preferences: ^0.5.7+3
  path_provider: ^1.6.9
  equatable: ^1.1.1
  animations: ^1.0.0+5
  webview_flutter: ^0.3.22+1
  flare_flutter: ^2.0.3
  nima: ^1.0.5
  timeline_list: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lishu
      fonts:
        - asset: fonts/ZhiMangXing-Regular.ttf
          style: normal
    - family: RegularScript
      fonts:
        - asset: fonts/NotoSansSC-Regular.otf
          style: normal
        - asset: fonts/NotoSansSC-Medium.otf
          weight: 500
        - asset: fonts/NotoSansSC-Bold.otf
          weight: 700
        - asset: fonts/NotoSansSC-Black.otf
          style: normal
        - asset: fonts/NotoSansSC-Light.otf
          style: normal
        - asset: fonts/NotoSansSC-Thin.otf
          style: normal

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
